# Generated by Django 4.1.5 on 2023-02-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_adress_users_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='adress',
            new_name='Adress',
        ),
        migrations.RenameField(
            model_name='artisan',
            old_name='state',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='artisan',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user',
            new_name='User',
        ),
    ]
