# Generated by Django 4.1.5 on 2023-02-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_adress_artisan_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Vender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Bank',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Number_bank',
            field=models.IntegerField(null=True),
        ),
    ]
