# Generated by Django 4.1.5 on 2023-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users_vender_alter_artisan_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Vender',
        ),
        migrations.AddField(
            model_name='users',
            name='Action',
            field=models.IntegerField(blank=True, choices=[(1, 'Vender'), (2, 'Comprar')], default=2, null=True),
        ),
    ]
