# Generated by Django 4.1.5 on 2023-02-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_users_vender_users_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Action',
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Documento',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='artisans'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Documento',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
