# Generated by Django 4.1.5 on 2023-02-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=45)),
                ('Description', models.TextField()),
                ('Characteristics', models.TextField()),
                ('stock', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Discount', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Images', models.ImageField(upload_to='products')),
                ('Size', models.CharField(blank=True, max_length=4, null=True)),
                ('Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('Material', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.IntegerField()),
                ('Coment', models.CharField(max_length=255)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product')),
            ],
        ),
    ]
