# Generated by Django 4.1.5 on 2023-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_artisan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.IntegerField(choices=[(1, 'Artesania Indigena'), (2, 'Pinturas'), (3, 'Bordados'), (4, 'Tejidos'), (5, 'Carpinteria'), (6, 'Alfareria'), (7, 'artesania Reciclada'), (8, 'Decoracion y regalos'), (9, 'Otra')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Characteristics',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('U', 'Unisex')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, null=True),
        ),
    ]
