# Generated by Django 4.1.5 on 2023-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_rename_stock_product_stock_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Products')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Images',
        ),
        migrations.AddField(
            model_name='product',
            name='Images',
            field=models.ManyToManyField(blank=True, to='shop_app.image'),
        ),
    ]
