# Generated by Django 4.1.5 on 2023-02-08 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0004_image_remove_product_images_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='Gender',
            field=models.CharField(blank=True, choices=[('N', 'No aplica'), ('F', 'Femenino'), ('M', 'Masculino'), ('U', 'Unisex')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(blank=True, choices=[('NA', 'No aplica'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, null=True),
        ),
    ]
