# Generated by Django 4.1.5 on 2023-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_product_artisan_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrincipalImage',
            field=models.ImageField(blank=True, null=True, upload_to='Products'),
        ),
    ]
